[package]
name = "stringsext"
version = "1.99.3"
authors = ["Jens Getreu <getreu@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs= "*"
lazy_static = "*"
docopt = "*"
serde = "*"
serde_derive = "*"
itertools = "*"
scoped_threadpool = "*"
anyhow = "*"
